# Site settings
title: 'HuntFunc Happenings' # Your Title
tagline: 'HSV devs speak on important topics' # A brief tagline for your site
sidebar_image: /images/solvay.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: # the subpath of your site, e.g. /blog/
