# Site settings
title: "HuntFunc Happenings"
header-img: "img/fpfolks.jpg"
email: huntfunc@googlegroups.com
description: "Huntsville folks becoming functional"
baseurl: ""
url: "http://huntfunc.github.io"
twitter_username: HuntFunc
github_username:  huntfunc
#facebook_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
